name: Deploy dev environment

on:
    push:
        branches: [develop]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              id: build-step
              run: |
                  echo "BUILD_ENV=installing dependencies" >> $GITHUB_ENV
                  echo "BUILD_ENV=installing dependencies" >> $GITHUB_OUTPUT
        outputs:
            BUILD_ENV: ${{ steps.build-step.outputs.BUILD_ENV }}
    deploy:
        needs: build
        name: deploy
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ needs.build.outputs.BUILD_ENV }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              id: deploy-step
              run: |
                  echo $BUILD_ENV
                  echo "DEPLOY_ENV=deploying to dev ${BUILD_ENV}" >> $GITHUB_ENV
                  echo "DEPLOY_ENV=deploying to dev ${BUILD_ENV}" >> $GITHUB_OUTPUT
        outputs:
            DEPLOY_ENV: ${{ steps.deploy-step.outputs.DEPLOY_ENV }}
    post-deploy:
        needs: deploy
        name: Post deploy
        runs-on: ubuntu-latest
        env:
            DEPLOY_ENV: ${{ needs.deploy.outputs.DEPLOY_ENV }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Post deploy
              run: echo "Post deploy to dev ${DEPLOY_ENV}"
            - name: Create PR to temp branch
              run: gh pr create --base develop --head temp --title "Create temp PR" --body "${DEPLOY_ENV}"
            - name: Create PR to temp staging branch
              run: gh pr create --base temp --head staging --title "Create staging PR" --body "${DEPLOY_ENV}"
