name: Deploy dev environment

on:
    push:
        branches: [develop]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: BUILD_ENV="installing dependencies"
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              run: |
                  echo $BUILD_ENV
                  DEPLOY_ENV="deploying to dev $BUILD_ENV"
    post-deploy:
        name: Post deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Post deploy
              run: echo "Post deploy to dev ${DEPLOY_ENV}"
            - name: Create PR to temp branch
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "Create temp PR"
                  body: ${{ env.DEPLOY_ENV }}
                  branch: "develop"
                  base: "temp"
                  labels: "automated"
            - name: Create PR to temp staging branch
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "Create staging PR"
                  body: ${{ env.DEPLOY_ENV }}
                  branch: "develop"
                  base: "staging"
                  labels: "automated"
