name: Deploy dev environment

on:
    push:
        branches: [staging]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: BUILD_ENV="installing dependencies"
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              run: |
                  echo BUILD_ENV
                  DEPLOY_ENV="deploying to staging $BUILD_ENV"
    post-deploy:
        name: Post deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Post deploy
              run: echo "Post deploy to staging $DEPLOY_ENV"
            - name: Create PR to temp branch
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "Create temp PR"
                  body: ${{ env.DEPLOY_ENV }}
                  branch: "staging"
                  base: "main"
                  labels: "automated"