name: Deploy temp environment

on:
    push:
        branches: [temp]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              id: build-step
              run: |
                  echo "BUILD_ENV=installing dependencies" >> $GITHUB_ENV
                  echo "BUILD_ENV=installing dependencies" >> $GITHUB_OUTPUT
        outputs:
            BUILD_ENV: ${{ steps.build-step.outputs.BUILD_ENV }}
    deploy:
        needs: build
        name: deploy
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ needs.build.outputs.BUILD_ENV }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              run: |
                  echo "deploying to temp ${BUILD_ENV}"
