name: Deploy dev environment

on:
    push:
        branches: [temp]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: echo "BUILD_ENV=installing dependencies" >> $GITHUB_ENV
            - name: Pass env to deploy
              run: echo "BUILD_ENV=${BUILD_ENV}" >> $GITHUB_OUTPUT
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        env:
            BUILD_ENV: ${{ steps.build.outputs.BUILD_ENV }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              run: |
                  echo "deploying to temp ${BUILD_ENV}"
