name: Deploy dev environment

on:
    push:
        branches: [temp]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: BUILD_ENV="installing dependencies"
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Deploy
              run: |
                  echo "deploying to temp ${BUILD_ENV}"
